server {
    listen 80;
    listen [::]:80;
    server_name ifconfig.fyi www.ifconfig.fyi;

    client_max_body_size 1M;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
