name: Bug Report
description: Report a bug
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
